// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: api/api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClientServerTxnsClient is the client API for ClientServerTxns service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientServerTxnsClient interface {
	Request(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Reply, error)
}

type clientServerTxnsClient struct {
	cc grpc.ClientConnInterface
}

func NewClientServerTxnsClient(cc grpc.ClientConnInterface) ClientServerTxnsClient {
	return &clientServerTxnsClient{cc}
}

func (c *clientServerTxnsClient) Request(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/api.ClientServerTxns/Request", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServerTxnsServer is the server API for ClientServerTxns service.
// All implementations must embed UnimplementedClientServerTxnsServer
// for forward compatibility
type ClientServerTxnsServer interface {
	Request(context.Context, *Message) (*Reply, error)
	mustEmbedUnimplementedClientServerTxnsServer()
}

// UnimplementedClientServerTxnsServer must be embedded to have forward compatible implementations.
type UnimplementedClientServerTxnsServer struct {
}

func (UnimplementedClientServerTxnsServer) Request(context.Context, *Message) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedClientServerTxnsServer) mustEmbedUnimplementedClientServerTxnsServer() {}

// UnsafeClientServerTxnsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientServerTxnsServer will
// result in compilation errors.
type UnsafeClientServerTxnsServer interface {
	mustEmbedUnimplementedClientServerTxnsServer()
}

func RegisterClientServerTxnsServer(s grpc.ServiceRegistrar, srv ClientServerTxnsServer) {
	s.RegisterService(&ClientServerTxns_ServiceDesc, srv)
}

func _ClientServerTxns_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServerTxnsServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ClientServerTxns/Request",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServerTxnsServer).Request(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientServerTxns_ServiceDesc is the grpc.ServiceDesc for ClientServerTxns service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientServerTxns_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ClientServerTxns",
	HandlerType: (*ClientServerTxnsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _ClientServerTxns_Request_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}
